# Generated by Django 4.0.4 on 2022-05-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile-pics'),
        ),
    ]
