# Generated by Django 4.0.4 on 2022-05-24 02:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_bloguser_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogUser',
            new_name='Profile',
        ),
    ]
