# Generated by Django 4.0.4 on 2022-05-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, default='default-post.jpg', upload_to='post-pics'),
        ),
    ]
