# Generated by Django 4.0.4 on 2022-05-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_pic',
            new_name='foto_post',
        ),
    ]
