# Generated by Django 4.0.4 on 2022-05-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_post_pic_post_foto_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto_post',
            field=models.ImageField(default='default-post.jpg', upload_to='post-pics'),
        ),
    ]
