# Generated by Django 4.0.4 on 2022-05-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_foto_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto_post',
            field=models.ImageField(blank=True, default='default-post.jpg', null=True, upload_to='post-pics'),
        ),
    ]
